version: '3'

services:
  db:
    build:
      context: ../.. 
      dockerfile: infrastructure/prod/dockerfiles/database.Dockerfile
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Max1
      MYSQL_DATABASE: to_do
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3307:3306"
    networks:
      - backend

  backend:
    build:
      context: ../.. #path relativo a docker-compose file che indica da dove partire per trovare il dockerfile
      dockerfile: infrastructure/prod/dockerfiles/backend.Dockerfile
    ports:
      - '3001:3001' #host:container
    networks:
      - backend
    depends_on:
      - db

  frontend:
    build:
      context: ../..
      dockerfile: infrastructure/prod/dockerfiles/frontend.Dockerfile
    ports:
      - '3000:3000'
    networks:
      - backend

networks:
  backend:

volumes:
  db_data:
